version: "3.8"
services:
  db:
    image: postgres:18
    container_name: pg-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d   # tus .sql se ejecutan automáticamente
    restart: unless-stopped

volumes:
  pgdata:
